services:
  php:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    container_name: php-timetracker
    ports:
      - "8000:8000"
    volumes:
      - ./php:/var/www/html
      - vendor_volume:/var/www/html/vendor
  mysql:
    build:
      context: .
      dockerfile: ./infra/mysql/Dockerfile
    ports:
      - "3307:3306"
    environment:
      - "LANG=C.UTF-8"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=timetracker"
    volumes:
      - type: volume
        source: mysql-volume
        target: /var/lib/mysql

networks:
  default:
    driver: bridge

volumes:
  vendor_volume:
    driver: local
  mysql-volume:
    driver: local